<?php
  $library_path = 'twitter-api-php-master';
  
  $twitter_info = [ 
    'hashtag' => '#envivo',
    'url' => '/envivo',
    'account' => 'fortalezapr',
  ];

  $ustream = [  
    'dev_key' => '4D1869A6089C22AC737C29A041DE4ACC',
    'channel' => 'fortalezapr',
  ];

  $twitter_crendentials= [
    'oauth_token' => '24695635-bxsWVQc2gRPSs1hbSoSUvVo1rMz94jCdDuB0rJMuw',
    'oauth_secret' => 'AIRLt1lSircRl8E0ylLatHtLN0u6AkZ0WsfjzoDRtQ',
    'consumer_key' =>  'I8Tj5c0WselYcA1pAQRzfg',
    'consumer_secret' => 'pcaoknLiJC1YQxsrJEEFL3MQTVCxj8Za4a4xUQSTQzY',
  ];